#!/usr/bin/env python3
"""Regenerate AGENTS.md from the catalog. Run from the package root:

    python scripts/gen_agents_md.py > AGENTS.md

Keeping the table generated (not hand-edited) means the catalog in
``catalog.py`` is the single source of truth.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parents[1] / "src"))

from acp_registry import ACP_AGENTS, by_status  # noqa: E402
from acp_registry.catalog import (  # noqa: E402
    CATALOG,
    NATIVE,
    OUT_OF_SCOPE,
    RUNNABLE,
    VENDOR_LOCKED,
    WIRED,
)

_SNAPSHOT = json.loads(
    (Path(__file__).parents[1] / "registry.snapshot.json").read_text()
)
# (emoji, label) per status — kept as separate fields so render sites never
# re-parse a fused string.
_BADGE = {
    NATIVE: ("🟦", "native"),
    WIRED: ("✅", "wired"),
    RUNNABLE: ("🏃", "runnable"),
    CATALOG: ("📋", "catalog"),
    VENDOR_LOCKED: ("🔒", "vendor-locked"),
    OUT_OF_SCOPE: ("➖", "out-of-scope"),
}
# Presentation order for the doc (most-actionable first).
_ORDER = (WIRED, RUNNABLE, CATALOG, NATIVE, VENDOR_LOCKED, OUT_OF_SCOPE)
_SECTION = {
    WIRED: (
        "Wired — registered + routes correctly by construction",
        "`register()` installs these. BenchFlow creates the experiment, routes the "
        "model through its gateway, and tracks BOTH the raw-LLM trajectory (proxy "
        "capture) AND the ACP-trajectory logs. Routing is verified *by construction* "
        "(confirmed env vars + a model format BenchFlow can emit); see the "
        "honesty bar in the README for what that does and doesn't claim.",
    ),
    RUNNABLE: (
        "Runnable — installs + launches headless, but model not gateway-enforced",
        "Install + launch headlessly in a benchflow task env: BenchFlow creates the "
        "experiment and tracks the **ACP-trajectory logs**, but the model runs on the "
        "agent's own/vendor backend so the **raw-LLM proxy is NOT captured** (per-agent "
        "caveats in each row). Executable, not a faithful model-controlled eval. "
        "**Pre-merge verified:** every committed `install_cmd` runs end-to-end (produces "
        "the launch binary) and the ACP handshake (initialize + session/new) succeeds; "
        "BenchFlow discovers these via the `acp/<id>/manifest.toml` loader (`register()` "
        "does not install them). Vendor-backed agents need their own creds at eval time.",
    ),
    CATALOG: (
        "Catalog — BYO-redirectable, recipe given, not yet wired",
        "These can be pointed at an arbitrary OpenAI/Anthropic-compatible base "
        "URL, so they're adaptable — each is held back only by something this "
        "npx-only first pass doesn't ship (a config-file writer, a binary "
        "installer, a uvx bootstrap, or a model-id format BenchFlow can't emit). "
        "The **Recipe** column is the exact next step to wire it.",
    ),
    NATIVE: (
        "Native — already a BenchFlow built-in",
        "BenchFlow ships these directly; use `--agent <built-in>`. Listed so the "
        "registry mapping is complete.",
    ),
    VENDOR_LOCKED: (
        "Vendor-locked — can't route through the gateway",
        "Authenticate only to their vendor's backend (no arbitrary base URL), so "
        "BenchFlow can't enforce the benchmark's model or capture usage. Not a "
        "faithful eval.",
    ),
    OUT_OF_SCOPE: (
        "Out of scope",
        "Not a single LLM coding/eval agent.",
    ),
}


def _link(agent) -> str:
    # Only hyperlink github.com repos (the markdown-link-check config ignores
    # those). Vendor URLs — many proprietary, some unstable — are shown as a
    # code span so the link checker never fetches them.
    repo = agent.repository
    if repo.startswith("https://github.com"):
        return f"[{agent.name}]({repo})"
    if repo:
        return f"{agent.name} (`{repo}`)"
    return agent.name


def main() -> None:
    out: list[str] = []
    total = len(ACP_AGENTS)
    ver = _SNAPSHOT.get("version", "?")
    out.append("<!-- GENERATED by scripts/gen_agents_md.py — do not edit by hand. -->")
    out.append("")
    out.append("# ACP registry → BenchFlow")
    out.append("")
    out.append(
        f"All **{total}** agents in the Agent Client Protocol registry "
        f"(snapshot `v{ver}`, see [`registry.snapshot.json`](registry.snapshot.json)), "
        "classified by whether they can run as a faithful, model-enforced BenchFlow "
        "eval. The bar for adaptation is **BenchFlow can create the experiment and "
        "track the run's logs**: `wired` + `native` capture both the raw-LLM "
        "trajectory (gateway proxy) and the ACP-trajectory logs; `runnable` captures "
        "the ACP-trajectory logs only (the model runs on the agent's own/vendor "
        "backend, so the LLM proxy is not captured). Source of truth: "
        "[`src/acp_registry/catalog.py`](src/acp_registry/catalog.py)."
    )
    out.append("")
    counts = " · ".join(
        f"{_BADGE[s][1]}: {len(by_status(s))}" for s in _ORDER
    )
    out.append(f"**Tally:** {counts}.")
    out.append("")

    for status in _ORDER:
        agents = by_status(status)
        if not agents:
            continue
        title, blurb = _SECTION[status]
        out.append(f"## {_BADGE[status][1].title()} ({len(agents)})")
        out.append("")
        out.append(blurb)
        out.append("")
        if status == WIRED:
            out.append("| Agent | id | License | api_protocol | Verified | Notes |")
            out.append("|---|---|---|---|---|---|")
            for a in agents:
                verified = ", ".join(a.verified) if a.verified else "—"
                notes = a.reason
                if a.known_issue:
                    notes += f" **Known issue:** {a.known_issue}"
                out.append(
                    f"| {_link(a)} | `{a.registry_id}` | {a.license} | "
                    f"`{a.api_protocol}` | {verified} | {notes} |"
                )
        elif status == CATALOG:
            out.append("| Agent | id | License | Dist | Recipe to wire |")
            out.append("|---|---|---|---|---|")
            for a in agents:
                out.append(
                    f"| {_link(a)} | `{a.registry_id}` | {a.license} | "
                    f"{a.distribution} | {a.reason} |"
                )
        elif status == NATIVE:
            out.append("| Agent | id | BenchFlow built-in |")
            out.append("|---|---|---|")
            for a in agents:
                out.append(
                    f"| {_link(a)} | `{a.registry_id}` | `--agent {a.native_name}` |"
                )
        else:
            out.append("| Agent | id | License | Why |")
            out.append("|---|---|---|---|")
            for a in agents:
                out.append(
                    f"| {_link(a)} | `{a.registry_id}` | {a.license} | {a.reason} |"
                )
        out.append("")

    out.append("---")
    out.append("")
    out.append(
        "Routing facts were researched from each agent's own docs/source on "
        "2026-06-13 (the `source` field on each catalog entry). Re-run "
        "`scripts/refresh_registry.py` to diff against the live registry."
    )
    out.append("")
    sys.stdout.write("\n".join(out))


if __name__ == "__main__":
    main()
